services:
  - type: worker
    name: zrg-oblivion-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: CLAN_NAME
        value: ZRG OBLIVION
      - key: DATA_DIR
        value: /data
      - key: CLAN_MEMBERS
        value: "59"
    disks:
      - name: zrg-data
        mountPath: /data
        sizeGB: 1

databases: []
